### PR TITLE
Fix a bunch of silly crashes.

### LINKED ISSUE #157: Segfault in Viewer Utility
## Steps to reproduce

  1. Compile the code; 
  2. run viewer with a scene without providing the navmesh;
  3.

## Observed Results

   segfault.

## Expected Results

  Viewer should performs as a virtual touring system for the scene.

## Relevant Code

The problem comes from the following line in viewer.cpp
```
const vec3f position = pathfinder_->getRandomNavigablePoint();

```
It segfaults if the pathfinder is not initialized before this line. 

@aclegg3

### PR DESCRIPTION
**Pull request by mosra**
## Motivation and Context

First commit fixes #157, accessing pathfinder only if it's loaded. Reproducible by doing the following:

```sh
cd path/to/mp3d/82sE5b5pLXE
path/to/viewer 82sE5b5pLXE_semantic.ply    # boom, there's no 82sE5b5pLXE_semantic.navmesh
```

Second commit fixes the following:

```sh
cd path/to/any/house
path/to/viewer house.json         # boom
path/to/viewer $(pwd)/house.json  # doesn't boom
```

## How Has This Been Tested

Doesn't crash as much as before -- however the pathfinder should be more robust I think, accessing it while it's not loaded should not segfault.

### CODE REVIEW

File: src/esp/assets/ResourceManager.cpp [hunk 1]
```diff
@@ -1099,10 +1102,12 @@ bool ResourceManager::loadSUNCGHouseFile(const AssetInfo& houseInfo,
                                          scene::SceneNode* parent,
                                          DrawableGroup* drawables) {
   ASSERT(parent != nullptr);
-  const std::string& houseFile = houseInfo.filepath;
+  std::string houseFile = Cr::Utility::Directory::join(
```
Comment (erikwijmans) [inline src/esp/assets/ResourceManager.cpp]: Maybe only do this if the path doesn't exist?  Otherwise people always have to specify a relative path.

Comment (mosra) [reply src/esp/assets/ResourceManager.cpp]: It always exists ;) ... only it's relative in some cases (relative to CWD) and absolute in others -- in both cases `exists()` returns `true`.

And, (I think I mentioned this a few times already) `join()` works the same as Python's `os.path.join()` -- so if you `join(whatever, absolutePath)`, you *always* get `absolutePath` unchanged.

Comment (erikwijmans) [reply src/esp/assets/ResourceManager.cpp]: Ah!  I didn't know python's `join` did that :)

Comment (mosra) [reply src/esp/assets/ResourceManager.cpp]: In my opinion that's *the* main feature of it that makes `join()` so immensely useful and failproof :)
